export const DARTS_STICKER_SET = {
    PREPARING: "CAACAgEAAxkBAAOCZd9Bvyp_JXq7cHvdZUXhr0GYCN8AAjoIAALjeAQAAefsaijl2VZkNAQ",
    WIN_0: "CAACAgEAAxkBAAOGZd9CXzG1pKYqmwMvHcS_-cIaX-UAAjMIAALjeAQAAXbxbYZrbVydNAQ",
    WIN_1: "CAACAgEAAxkBAAOJZd9Cx4vXWXomV9RY3XCqFb6McCcAAjQIAALjeAQAAUE2RQ3bHHuFNAQ",
    WIN_2: "CAACAgEAAxkBAAOLZd9DBCROmixccfBOWQOpZDa9SK4AAjUIAALjeAQAAR03dTXGTcw-NAQ",
    WIN_3: "CAACAgEAAxkBAAOOZd9DNmekWMXS2gO0DanBdEH2-eoAAjYIAALjeAQAAZZdCQ3cnl3SNAQ",
    WIN_4: "CAACAgEAAxkBAAORZd9DamD4Vf1N2-LFpPimTfTtIl8AAjcIAALjeAQAASoYP9ZaHkh_NAQ",
    WIN_5: "CAACAgEAAxkBAAOTZd9DhO6dOHrZ8wAB_L_iA6znTpRBAAI4CAAC43gEAAFoga8ZQFZTfTQE",
};
